### ISSUE TITLE
Scala 2.10

### ISSUE THREAD

**Issue by ardlema** [velvia/ScalaStorm#12]
Hi there!

Are you supporting Scala 2.10? When trying to add the velvia dependencies to my Scala 2.10 project I am getting the following error:

sbt.ResolveException: unresolved dependency: com.github.velvia#scala-storm_2.10;0.2.2

Thank you in advance!

**Comment by matanster** [comment]
`build.sbt` already uses 2.10 and 2.11, so why actually is this still open?

**Comment by velvia** [comment]
@matanster good point.
