### ISSUE TITLE
Publish to maven for 2.11

### ISSUE THREAD

**Issue by papaonlegs** [velvia/ScalaStorm#23]
Your current master branch compiles for 2.11. Could you please push a jar to mvnrepository?

**Comment by papaonlegs** [comment]
Any news on this? It already compiles to 2.11 but would be great if you could publish the artefact like you did with [this](http://search.maven.org/#search%7Cga%7C1%7Cscala-storm)

**Comment by aerios** [comment]
+1. Publishing this to mvnrepository will greatly improve our development cycle

**Comment by papaonlegs** [comment]
I've just emailed the owner directly

**Comment by velvia** [comment]
I have published a snapshot for now.

[info] 	published scala-storm_2.11 to https://oss.sonatype.org/content/repositories/snapshots/com/github/velvia/scala-storm_2.11/0.2.5-SNAPSHOT/scala-storm_2.11-0.2.5-SNAPSHOT.jar
